import './globals.css'
import localFont from 'next/font/local'
import 'bootstrap/dist/css/bootstrap.css'
import Footer from './footer';
import Header from './header'

const helveticaBold = localFont({ src: './fonts/Helvetica_Bold.ttf', variable:'--helvetica-bold-font' })
const helveticaRegular = localFont({ src: './fonts/Helvetica_Regular.otf', variable:'--helvetica-regular-font'})
const microsoftSans = localFont({ src: './fonts/micross.ttf', variable:'--microsoft-sans-font' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{
        '--bs-body-color':'#4D5156',
          '--bs-body-font-family':microsoftSans.style.fontFamily,
          '--helvetica-bold-font': helveticaBold.style.fontFamily,
         '--helvetica-regular-font': helveticaRegular.style.fontFamily,
          '--microsoft-sans-font': microsoftSans.style.fontFamily,
          '--text-color-crimson':'#DC143C',
          '--text-color-shark':'#202124',
          '--text-color-abbey':'#4D5156',
        }}>
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  )
}
