name: Deploy CRM to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push CRM Docker image
        run: |
          docker build -t yudhishthira/crm:latest .
          docker push yudhishthira/crm:latest

      - name: Debug Host
        run: echo "Host is ${{ secrets.EC2_HOST }}"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull yudhishthira/crm:latest
            docker stop crm || true
            docker rm crm || true
            docker run -d --name crm -p 81:80 yudhishthira/crm:latest
