name: Deploy Propify to EC2

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t yogesh-figma/propify-desktop:latest .

      - name: Push image to DockerHub
        run: docker push yogesh-figma/propify-desktop:latest

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull yogesh-figma/propify-desktop:latest
            docker stop propify-container || true
            docker rm propify-container || true
            docker run -d -p 3001:3000 --name propify-container yogesh-figma/propify-desktop:latest
